version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5433:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: chat_with_pdf
